import './globals.css'
import { Providers } from "./providers";
import { Roboto, Ephesis } from '@next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: '400',
  display: 'swap'
});

const other = Ephesis({
  subsets: ['latin'],
  variable: '--font-other',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${other.variable} ${roboto.variable} light`}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
